CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(100),
	NOME_AUTOR VARCHAR(100),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAG INT(100),
	NOME_EDITORA VARCHAR(100),
	VALOR_LIVRO FLOAT(100,2),
	ESTADO_EDITORA CHAR(2),
	ANO_PUBLICACAO VARCHAR(30)
);


INSERT INTO LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR, NUMERO_PAG, NOME_EDITORA,
 VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES ('A bússola de oura','Philip Pullman','m', 500, 'Ilumnar',200.00, 'SP','2001');